title: BIRDWATCHER

description: identify the bird in the given image.

about: Birdwatcher aims to help Texas' birdwatching enthusiasts in quickly identifying a bird from its image. This project uses a finetuned resnet18 trained on bird images from 10 different classes. The dataset was created using bing image search.


code: https://github.com/wildfiredev1/birdwatcher


sampleImages:
  - name: American Coot
    url: http://4.bp.blogspot.com/-FlfiArJS_5k/VP5c4_WDVhI/AAAAAAAAWlg/41taj74CRnE/w1200-h630-p-k-no-nu/coot.jpg
  - name: Blue Jay
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Blue_jay_in_PP_%2830960%29.jpg/220px-Blue_jay_in_PP_%2830960%29.jpg
  - name: Great Blue Heron
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Great_blue_heron_%28Ardea_herodias_occidentalis%29_white_form.JPG/220px-Great_blue_heron_%28Ardea_herodias_occidentalis%29_white_form.JPG
  - name: Cattle Egret
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/1/1d/Cattle_Egret_in_breeding_plumage%2C_Wakodahatchee_Wetlands.jpg/220px-Cattle_Egret_in_breeding_plumage%2C_Wakodahatchee_Wetlands.jpg
  - name: Eastern Screech Owl
    url: https://i.pinimg.com/originals/3c/ae/bd/3caebdec0659528b31503ac27f69000a.jpg
  - name: Neotropic Cormorant
    url: http://www.oiseaux-birds.com/pelecaniformes/phalacrocoracides/cormoran-vigua/cormoran-vigua-tg1.jpg
  - name: Northern Mockingbird
    url: https://nas-national-prod.s3.amazonaws.com/a1_7448_5_northern-mockingbird_craig_abbott_adult.jpg
  - name: Red Headed Woodpecker
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Melanerpes-erythrocephalus-003.jpg/220px-Melanerpes-erythrocephalus-003.jpg
  - name: Redtailed Hawk
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Red-tailed_Hawk.jpg/220px-Red-tailed_Hawk.jpg
  - name: Barn Owl
    url: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c6/Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg/220px-Tyto_alba_-British_Wildlife_Centre%2C_Surrey%2C_England-8a_%281%29.jpg
